### ISSUE TITLE
Why this is inference only but not for training?

### ISSUE THREAD

**Issue by spacegoing** [xdit-project/xDiT#164]
I'd love to know if hybrid parallel implemented here is suitable for training?

And why not?

**Comment by feifeibear** [comment]
PipeFusion is not intended for training, as it leverages input temporal redundancy, which is only present during inference. Sequence parallelism, USP in xDiT, is inherently applicable to LLM training.

Training DiT is straightforward due to its small model size and long sequence length; ZeRO combined with USP can handle it effectively. 

Consequently, training is naive, but inference presents more of a challenge.
