### ISSUE TITLE
Performance Degradation Under High Concurrency with xDiT Framework

### ISSUE THREAD

**Issue by faceeyes** [xdit-project/xDiT#311]
Hello,

I am currently using the xDiT framework in my project, and I have encountered performance issues under high concurrency scenarios. Specifically, when the number of concurrent requests increases, the performance of the application drops significantly, which does not meet our expectations.

Could you please provide some guidance or suggestions on how to optimize performance under such conditions? Are there any best practices, configuration adjustments, or alternative strategies that could help improve the situation?

Thank you for your attention and assistance!

Best regards

**Comment by feifeibear** [comment]
Hello, how do you serve multiple requests? Do you batch them together for a single generation, or do you start multiple processes, each handling one request?

**Comment by faceeyes** [comment]
Thank you for your prompt response and attention to my question. Currently, I am using comfyUI alongside xDiT. From my understanding, concurrent requests are queued and processed sequentially; therefore, I haven't implemented batching nor have I started multiple processes to handle each request individually. This setup seems to be a bottleneck when dealing with high concurrency.

To increase the speed of processing requests, I'm considering a scenario where I use four GPUs. Would it be more efficient to increase the batch size and utilize the pipefusion method for parallel processing across all four cards? Alternatively, should I opt for running four separate processes, each utilizing a single GPU to handle individual requests independently? Or are there other solutions or recommendations that might better suit my needs and improve performance under high concurrency?

Thank you for your assistance!

**Comment by feifeibear** [comment]
I think you should clarify two metrics, **latency** and **throughput**.

If you are using multiple GPUs to reduce the latency of generating a single image, your throughput will decrease. This is because using multiple GPUs introduces communication overhead, even though we use techniques like USP and Pipefusion to minimize the communication cost.

 Using batching will increase latency but may improve throughput. If you don't care about latency, the optimal solution is to have one GPU process one image.
 
 I think you need to balance latency and throughput.
 
 
 We have a multiple GPU comfyui solution. You can refer to this blog.
 https://medium.com/p/54b34e4bca05

**Comment by faceeyes** [comment]
Thanks for the insights and the blog link. I'll review it and consider the trade-offs between latency and throughput.

Appreciate your help!

Best regards
