### ISSUE TITLE
why cogvideo only support 4gpus dit parallel?

### ISSUE THREAD

**Issue by Bensong0506** [xdit-project/xDiT#358]
Hi,

Very good work for accelerating dit. But why do you set sp_degree == ulysses_degree*ring_degree <= 2 in Cogvideo? Will ulysses_degree = ring_degree = 2 slow down the model or it is just not implemented yet?

**Comment by Bensong0506** [comment]
Or is there a way I still input 8 gpus but I just let 4 gpus doing parallel inference, and 8 gpus doing encoder and decoder?

**Comment by xibosun** [comment]
We slice the video in the latent space in the height dimension and distribute each video patch to a GPU. Since the height (30) of the latent space is not divisible by 4, the sp_degree cannot be 4. You can try other configurations, e.g., ulysses_degree=3, ring_degree=2. Also CogVideoX in xDiT does not support parallel VAE, please do not use the "--use_parallel_vae" flag in CogVideoX inference.

**Comment by Bensong0506** [comment]
Thanks a lot!
